"""Canonical error codes (Architecture.md §5.5).

Every WARN+ debug event MUST carry an error_code from this registry.
"""

# Data errors
STALE_DATA = "STALE_DATA"
MISSING_FUNDAMENTAL_DATA = "MISSING_FUNDAMENTAL_DATA"
FX_RATE_UNAVAILABLE = "FX_RATE_UNAVAILABLE"
CORP_ACTION_UNHANDLED = "CORP_ACTION_UNHANDLED"
UNIVERSE_ROTATION = "UNIVERSE_ROTATION"
SECTOR_ETF_MISSING = "SECTOR_ETF_MISSING"
RATE_LIMIT_BLOCKED = "RATE_LIMIT_BLOCKED"
LIMITED_HISTORY_TICKER = "LIMITED_HISTORY_TICKER"
CALIBRATION_GAP_NEW_SYMBOL = "CALIBRATION_GAP_NEW_SYMBOL"

# LLM errors
GBNF_PARSE_FAIL = "GBNF_PARSE_FAIL"
LLM_TIMEOUT = "LLM_TIMEOUT"
LLM_CONNECTION_REFUSED = "LLM_CONNECTION_REFUSED"
LLM_OUTPUT_EMPTY = "LLM_OUTPUT_EMPTY"
SANITY_VALIDATION_FAIL = "SANITY_VALIDATION_FAIL"
MODEL_HASH_MISMATCH = "MODEL_HASH_MISMATCH"
GRAMMAR_VERSION_MISMATCH = "GRAMMAR_VERSION_MISMATCH"
ABORTED_LLM = "ABORTED_LLM"
PROMPT_INJECTION_DETECTED = "PROMPT_INJECTION_DETECTED"

# Arbitration / Pipeline errors
ARBITRATION_DISAGREEMENT = "ARBITRATION_DISAGREEMENT"
CRUCIBLE_SEVERITY_EXCEEDED = "CRUCIBLE_SEVERITY_EXCEEDED"
CRUCIBLE_BUDGET_EXCEEDED = "CRUCIBLE_BUDGET_EXCEEDED"
EV_BELOW_MINIMUM = "EV_BELOW_MINIMUM"
PORTFOLIO_RISK_GATE_BLOCKED = "PORTFOLIO_RISK_GATE_BLOCKED"
SIZING_CAPPED = "SIZING_CAPPED"

# Execution errors
TRADE_REJECTED = "TRADE_REJECTED"
TRADE_TIMEOUT = "TRADE_TIMEOUT"
BROKER_CONNECTION_FAILED = "BROKER_CONNECTION_FAILED"
SIGNING_KEY_NOT_FOUND = "SIGNING_KEY_NOT_FOUND"
SIGNATURE_VERIFICATION_FAILED = "SIGNATURE_VERIFICATION_FAILED"
CATASTROPHE_CANCEL_FAILED = "CATASTROPHE_CANCEL_FAILED"
CATASTROPHE_NET_FAILED = "CATASTROPHE_NET_FAILED"
ALPACA_ADAPTER_ERROR = "ALPACA_ADAPTER_ERROR"

# System errors
KILL_SWITCH_ENGAGED = "KILL_SWITCH_ENGAGED"
CRASH_LOOP_DETECTED = "CRASH_LOOP_DETECTED"
AUDIT_CHAIN_BREAK = "AUDIT_CHAIN_BREAK"
AUDIT_REPLICATION_FAILED = "AUDIT_REPLICATION_FAILED"
AUDIT_REPLICATION_DEGRADED = "AUDIT_REPLICATION_DEGRADED"
AUDIT_REPLICATION_CORRUPTION = "AUDIT_REPLICATION_CORRUPTION"
PROCESS_HEARTBEAT_MISSED = "PROCESS_HEARTBEAT_MISSED"
DISK_SPACE_LOW = "DISK_SPACE_LOW"
CLOCK_DRIFT_DETECTED = "CLOCK_DRIFT_DETECTED"

# Storage errors
CROSS_DB_INCONSISTENCY = "CROSS_DB_INCONSISTENCY"
QDRANT_WRITE_FAILED = "QDRANT_WRITE_FAILED"
QDRANT_QUERY_FAILED = "QDRANT_QUERY_FAILED"
QDRANT_CREATE_FAILED = "QDRANT_CREATE_FAILED"
QDRANT_EMBEDDING_FAILED = "QDRANT_EMBEDDING_FAILED"
QDRANT_CONNECTION_FAILED = "QDRANT_CONNECTION_FAILED"
KUZU_WRITE_FAILED = "KUZU_WRITE_FAILED"
KUZU_QUERY_FAILED = "KUZU_QUERY_FAILED"
KUZU_CONNECTION_FAILED = "KUZU_CONNECTION_FAILED"
KUZU_THESIS_QUERY_FAILED = "KUZU_THESIS_QUERY_FAILED"
DUCKDB_WRITE_FAILED = "DUCKDB_WRITE_FAILED"
FLYWHEEL_QUERY_FAILED = "FLYWHEEL_QUERY_FAILED"
SQLITE_WRITE_FAILED = "SQLITE_WRITE_FAILED"

# Mutation errors
MUTATION_SANITY_CHECK_FAILED = "MUTATION_SANITY_CHECK_FAILED"
MUTATION_ROLLBACK_FAILED = "MUTATION_ROLLBACK_FAILED"
MUTATION_PERMISSION_DENIED = "MUTATION_PERMISSION_DENIED"
MUTATION_FLAGGED_FOR_REVIEW = "MUTATION_FLAGGED_FOR_REVIEW"

# Catalyst resolution errors (Architecture.md §7)
CATALYST_TIMEOUT = "CATALYST_TIMEOUT"
CORROBORATION_OUTLIER = "CORROBORATION_OUTLIER"
CATALYST_RESOLUTION_ERROR = "CATALYST_RESOLUTION_ERROR"

# FDE errors
FDE_CLASSIFICATION_AMBIGUOUS = "FDE_CLASSIFICATION_AMBIGUOUS"

# Cycle hardening errors (Architecture.md §9)
GRACEFUL_SHUTDOWN = "GRACEFUL_SHUTDOWN"
CYCLE_INTERRUPTED = "CYCLE_INTERRUPTED"
HOLDINGS_INTERRUPTED = "HOLDINGS_INTERRUPTED"
PERSONA_TIMEOUT = "PERSONA_TIMEOUT"
CRUCIBLE_TIMEOUT = "CRUCIBLE_TIMEOUT"
STEP_OVER_BUDGET = "STEP_OVER_BUDGET"

# Pipeline / Orchestrator errors
DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
MEMO_WRITER_FAILED = "MEMO_WRITER_FAILED"
OPPORTUNITY_COST_FAILED = "OPPORTUNITY_COST_FAILED"
LEDGER_CONSTRAINT = "LEDGER_CONSTRAINT"
DB_WRITE_FAILED = "DB_WRITE_FAILED"

# Re-evaluation errors
REEVAL_FAILED = "REEVAL_FAILED"

# Dead letter queue errors
DLQ_EXHAUSTED = "DLQ_EXHAUSTED"

# Billing / cost accounting errors (Phase 16)
PRICING_FETCH_FAILED = "PRICING_FETCH_FAILED"
PRICING_MODEL_NOT_FOUND = "PRICING_MODEL_NOT_FOUND"
BUDGET_STATE_UPDATE_FAILED = "BUDGET_STATE_UPDATE_FAILED"
PERSONA_QUALITY_REGRESSION = "PERSONA_QUALITY_REGRESSION"
COST_RUNAWAY_DETECTED = "COST_RUNAWAY_DETECTED"
COST_CAP_BREACHED = "COST_CAP_BREACHED"
ESTIMATE_DRIFT = "ESTIMATE_DRIFT"
RECONCILIATION_FAILED = "RECONCILIATION_FAILED"

# SSE / web dashboard
SSE_CONNECTION_FAILED = "SSE_CONNECTION_FAILED"

# Sleep/wake detection (Architecture.md §4.6)
SLEEP_DETECTED = "SLEEP_DETECTED"
WAKE_DETECTED = "WAKE_DETECTED"

# Stop-loss monitoring
STOP_BREACH_DETECTED = "STOP_BREACH_DETECTED"
PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE"

# Web / HTTP errors
WEB_UNHANDLED_EXCEPTION = "WEB_UNHANDLED_EXCEPTION"

# Cash ledger
CASH_LEDGER_NEGATIVE_BALANCE = "CASH_LEDGER_NEGATIVE_BALANCE"
CASH_LEDGER_BALANCE_DRIFT = "CASH_LEDGER_BALANCE_DRIFT"

# Execution
EXEC_INVALID_PLAN = "EXEC_INVALID_PLAN"

# Price source failures
PRICE_POLYGON_FAILED = "PRICE_POLYGON_FAILED"
PRICE_FINNHUB_FAILED = "PRICE_FINNHUB_FAILED"
PRICE_ALPACA_FAILED = "PRICE_ALPACA_FAILED"

# Lesson / reconciliation
LESSON_WRITE_FAILED = "LESSON_WRITE_FAILED"
RECONCILIATION_CONFIG_PARSE_FAILED = "RECONCILIATION_CONFIG_PARSE_FAILED"

# Arbitration
ARBITRATION_MATURE_DISAGREE = "ARBITRATION_MATURE_DISAGREE"

# Orchestrator cycle events
CYCLE_MID_CYCLE_KILL_SWITCH = "CYCLE_MID_CYCLE_KILL_SWITCH"
CYCLE_SIGNAL_RECEIVED = "CYCLE_SIGNAL_RECEIVED"
CYCLE_STEP_BUDGET_EXCEEDED = "CYCLE_STEP_BUDGET_EXCEEDED"
CYCLE_ABORTED_CLOCK_DRIFT = "CYCLE_ABORTED_CLOCK_DRIFT"
CYCLE_ABORTED_KILL_SWITCH = "CYCLE_ABORTED_KILL_SWITCH"

# Flywheel
FLYWHEEL_HEALTH_CHECK = "FLYWHEEL_HEALTH_CHECK"

# Alpaca adapter
ALPACA_CANCEL_FAILED = "ALPACA_CANCEL_FAILED"

VALID_ERROR_CODES: frozenset[str] = frozenset({
    # Data
    STALE_DATA, MISSING_FUNDAMENTAL_DATA, FX_RATE_UNAVAILABLE,
    CORP_ACTION_UNHANDLED, UNIVERSE_ROTATION, SECTOR_ETF_MISSING,
    RATE_LIMIT_BLOCKED, LIMITED_HISTORY_TICKER, CALIBRATION_GAP_NEW_SYMBOL,
    # LLM
    GBNF_PARSE_FAIL, LLM_TIMEOUT, LLM_CONNECTION_REFUSED,
    LLM_OUTPUT_EMPTY, SANITY_VALIDATION_FAIL, MODEL_HASH_MISMATCH,
    GRAMMAR_VERSION_MISMATCH, ABORTED_LLM, PROMPT_INJECTION_DETECTED,
    # Arbitration
    ARBITRATION_DISAGREEMENT, CRUCIBLE_SEVERITY_EXCEEDED,
    CRUCIBLE_BUDGET_EXCEEDED, EV_BELOW_MINIMUM,
    PORTFOLIO_RISK_GATE_BLOCKED, SIZING_CAPPED,
    # Execution
    TRADE_REJECTED, TRADE_TIMEOUT, BROKER_CONNECTION_FAILED,
    SIGNING_KEY_NOT_FOUND, SIGNATURE_VERIFICATION_FAILED,
    CATASTROPHE_CANCEL_FAILED, CATASTROPHE_NET_FAILED,
    ALPACA_ADAPTER_ERROR,
    # System
    KILL_SWITCH_ENGAGED, CRASH_LOOP_DETECTED, AUDIT_CHAIN_BREAK,
    AUDIT_REPLICATION_FAILED, AUDIT_REPLICATION_DEGRADED,
    AUDIT_REPLICATION_CORRUPTION, PROCESS_HEARTBEAT_MISSED,
    DISK_SPACE_LOW, CLOCK_DRIFT_DETECTED,
    # Storage
    CROSS_DB_INCONSISTENCY, QDRANT_WRITE_FAILED, QDRANT_QUERY_FAILED,
    QDRANT_CREATE_FAILED, QDRANT_EMBEDDING_FAILED, QDRANT_CONNECTION_FAILED,
    KUZU_WRITE_FAILED, KUZU_QUERY_FAILED, KUZU_CONNECTION_FAILED,
    KUZU_THESIS_QUERY_FAILED, DUCKDB_WRITE_FAILED, FLYWHEEL_QUERY_FAILED, SQLITE_WRITE_FAILED,
    # Mutation
    MUTATION_SANITY_CHECK_FAILED, MUTATION_ROLLBACK_FAILED,
    MUTATION_PERMISSION_DENIED, MUTATION_FLAGGED_FOR_REVIEW,
    # Catalyst resolution (Architecture.md §7)
    CATALYST_TIMEOUT, CORROBORATION_OUTLIER, CATALYST_RESOLUTION_ERROR,
    # FDE
    FDE_CLASSIFICATION_AMBIGUOUS,
    # Cycle hardening
    GRACEFUL_SHUTDOWN, CYCLE_INTERRUPTED, HOLDINGS_INTERRUPTED,
    PERSONA_TIMEOUT, CRUCIBLE_TIMEOUT, STEP_OVER_BUDGET,
    # Pipeline / Orchestrator
    DATA_UNAVAILABLE, MEMO_WRITER_FAILED, OPPORTUNITY_COST_FAILED,
    LEDGER_CONSTRAINT, DB_WRITE_FAILED,
    # Dead letter queue
    DLQ_EXHAUSTED,
    # Re-evaluation
    REEVAL_FAILED,
    # Billing / cost accounting (Phase 16)
    PRICING_FETCH_FAILED, PRICING_MODEL_NOT_FOUND,
    BUDGET_STATE_UPDATE_FAILED, PERSONA_QUALITY_REGRESSION,
    COST_RUNAWAY_DETECTED, COST_CAP_BREACHED,
    ESTIMATE_DRIFT, RECONCILIATION_FAILED,
    # SSE / web dashboard
    SSE_CONNECTION_FAILED,
    # Sleep/wake detection (Architecture.md §4.6)
    SLEEP_DETECTED, WAKE_DETECTED,
    # Stop-loss monitoring
    STOP_BREACH_DETECTED, PRICE_UNAVAILABLE,
    # Web / HTTP errors
    WEB_UNHANDLED_EXCEPTION,
    # Cash ledger
    CASH_LEDGER_NEGATIVE_BALANCE, CASH_LEDGER_BALANCE_DRIFT,
    # Execution
    EXEC_INVALID_PLAN,
    # Price source failures
    PRICE_POLYGON_FAILED, PRICE_FINNHUB_FAILED, PRICE_ALPACA_FAILED,
    # Lesson / reconciliation
    LESSON_WRITE_FAILED, RECONCILIATION_CONFIG_PARSE_FAILED,
    # Arbitration
    ARBITRATION_MATURE_DISAGREE,
    # Orchestrator cycle events
    CYCLE_MID_CYCLE_KILL_SWITCH, CYCLE_SIGNAL_RECEIVED,
    CYCLE_STEP_BUDGET_EXCEEDED, CYCLE_ABORTED_CLOCK_DRIFT,
    CYCLE_ABORTED_KILL_SWITCH,
    # Flywheel
    FLYWHEEL_HEALTH_CHECK,
    # Alpaca adapter
    ALPACA_CANCEL_FAILED,
})
